name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -yqq --no-install-recommends \
          libcurl4-openssl-dev libopengl-dev libglew-dev \
          python3-hypothesis gobjc libgnustep-base-dev \
          libgomp1
    - run: ./configure
    - run: make
    - run: make check
  zig:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: mlugg/setup-zig@v2
      with:
        version: 0.13.0
    - run: zig build --summary all
    - run: zig build test --summary all
