name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        sudo apt install -yqq --no-install-recommends \
          libopengl-dev libglew-dev python3-setuptools
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make py
      run: make clean py
    - name: test py
      run: python3 hashtable_test.py
