name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -yqq --no-install-recommends \
          libcurl4-openssl-dev libopengl-dev libglew-dev \
          python3-hypothesis
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
  zig:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.12.0
    - run: zig build --summary all
    - run: zig build test --summary all
